### ISSUE TITLE
Consecutive local game or AI game have WS issue

### ISSUE THREAD

**Issue by Tsunghao-C** [Tsunghao-C/ft_Transcendence#95]
If you try to do two local games or AI games back to back, the second time will have WSDISCONNECT error and fail to start a game.
However, if you refresh the page and try it one more time, it can work.

Here is the exception message in the Django:
```
Exception inside application: 'room_name'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/channels/routing.py", line 48, in __call__
    return await application(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/channels/security/websocket.py", line 37, in __call__
    return await self.application(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/channels/sessions.py", line 44, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/channels/sessions.py", line 261, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/channels/auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/channels/middleware.py", line 24, in __call__
    return await self.inner(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/channels/routing.py", line 118, in __call__
    return await application(
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/channels/consumer.py", line 95, in app
    return await consumer(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/channels/consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "/usr/local/lib/python3.11/site-packages/channels/utils.py", line 50, in await_many_dispatch
    await dispatch(result)
  File "/usr/local/lib/python3.11/site-packages/channels/consumer.py", line 74, in dispatch
    await handler(message)
  File "/usr/local/lib/python3.11/site-packages/channels/generic/websocket.py", line 204, in websocket_receive
    await self.receive(text_data=message["text"])
  File "/home/app/pong-game/game_service/consumers.py", line 139, in receive
    await self.receive_methods[action](data)
  File "/home/app/pong-game/game_service/consumers.py", line 398, in update_ready_status
    room_name = data["room_name"]
                ~~~~^^^^^^^^^^^^^
KeyError: 'room_name'
WebSocket closed for ['172.19.0.5', 58494]
172.19.0.5:58494 - - [26/Dec/2024:12:09:04] "WSDISCONNECT /ws/game-server/test_game/" - -
```

**Comment by Tsunghao-C** [comment]
New findings about this error. It seems that when the url becomes /#[game_mode], the WS Connection is already created, and will never Disconnect automatically. 

When the url goes to /#solo/, in the backend the WS is connected. If you click Go back the WS is not disconnected automatically, so then when you try other game modes, the first try will always fail.
You will need to refresh the browser the rebuild the WS connection to the right game mode.

See the attached video and you will get a better understanding.

https://github.com/user-attachments/assets/9586df48-d24d-407a-82d0-40b5fb109945

**Comment by Haliris** [comment]
I am following the exact same steps from the screen recording and I cannot reproduce this bug.

Did you check that your branches are up to date?

**Comment by Tsunghao-C** [comment]
I checked again the latest main branch (#101) and there is not such issue. Maybe this WS connection logic is fixed already in previous PRs. I will close this issue for now.
